# Generated by Django 5.0.6 on 2024-05-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('processor_brand', models.CharField(max_length=100)),
                ('processor_tier', models.CharField(max_length=100)),
                ('num_cores', models.IntegerField()),
                ('num_threads', models.IntegerField()),
                ('ram_memory', models.IntegerField()),
                ('primary_storage_type', models.CharField(max_length=50)),
                ('primary_storage_capacity', models.IntegerField()),
                ('secondary_storage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_storage_capacity', models.IntegerField(blank=True, null=True)),
                ('gpu_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_touch_screen', models.BooleanField()),
                ('display_size', models.FloatField()),
                ('resolution_width', models.IntegerField()),
                ('resolution_height', models.IntegerField()),
                ('os', models.CharField(max_length=50)),
                ('year_of_warranty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=100)),
                ('cpu_intel', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_amd', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('ssd', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
