# Generated by Django 5.0.6 on 2024-06-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('Tip', 'Tip'), ('Info', 'Info')], max_length=4)),
                ('content', models.TextField()),
            ],
        ),
    ]
