# Generated by Django 5.0.6 on 2024-05-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=100)),
                ('cpu_intel', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_amd', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('ssd', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
