# Generated by Django 5.0.6 on 2024-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0004_laptoprecommendation2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='laptop_model',
        ),
        migrations.AddField(
            model_name='historial',
            name='brand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='gpu_brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historial',
            name='gpu_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historial',
            name='primary_storage_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historial',
            name='processor_brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historial',
            name='processor_tier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historial',
            name='secondary_storage_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
