# Generated by Django 5.0.6 on 2024-07-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0006_historial2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptoprecommendation2',
            name='user',
        ),
        migrations.DeleteModel(
            name='Historial2',
        ),
        migrations.DeleteModel(
            name='LaptopRecommendation2',
        ),
    ]
